# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/945afac1-211e-4747-a6f9-10efa36e2828";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/761ab582-4d11-457a-9216-93b91680e6a3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
